<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Adminer settings</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.0.5/css/adminlte.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.0.5/js/adminlte.min.js"></script>
    <script src="./settings.js"></script>
</head>
<body class="layout-top-nav">
    <form name="settings" method="post">
        <div class="wrapper">
            <nav class="main-header py-2">
                <div class="container text-right">
                    <a href="./" class="btn btn-outline-secondary">Back</a>
                    <input name="submit" type="submit" class="btn btn-outline-primary" value="Save">
                </div>
            </nav>
            <div class="content-wrapper">
                <main class="content">
                    <div class="container">
                        <h1>Settings</h1>
                        <div class="row">
                            <div class="col-md-12">
                                <?php if(!count($servers)): ?>
                                    <section class="card">
                                        <header class="card-header">
                                            <h2 class="card-title">Global settings</h2>
                                        </header>
                                        <div id="global-settings" class="card-body">
                                            <div class="form-group">
                                                <div class="form-check mt-2">
                                                    <input id="passwordless" name="passwordless" class="form-check-input" type="checkbox" value="1" <?=isset($config['passwordless'])&&$config['passwordless']?'checked':''?>>
                                                    <label for="passwordless" class="form-check-label">Passwordless</label>
                                                </div>
                                            </div>
                                        </div>
                                    </section>
                                <?php endif; ?>
                                <section class="card">
                                    <header class="card-header">
                                        <h2 class="card-title">Database servers</h2>
                                    </header>
                                    <div id="database-list" class="card-body"
                                        data-prototype="<fieldset class='shadow my-2 p-2'>
                                            <div class='row'>
                                                <div class='col'>
                                                    <div class='form-group'>
                                                        <label for='name-_ID_'>Name*</label>
                                                        <input id='name-_ID_' name='_ID_[name]' type='text' class='form-control' required>
                                                    </div>
                                                </div>
                                                <div class='col'>
                                                    <div class='form-group'>
                                                        <label for='server-_ID_'>Server</label>
                                                        <input id='server-_ID_'name='_ID_[server]' type='text' class='form-control' placeholder='127.0.0.1'>
                                                    </div>
                                                </div>
                                                <div class='col'>
                                                    <div class='form-group'>
                                                        <label for='port-_ID_'>Port</label>
                                                        <input id='port-_ID_' name='_ID_[port]' type='text' class='form-control' placeholder='3306'>
                                                    </div>
                                                </div>
                                                <div class='col'>
                                                    <div class='form-group'>
                                                        <label for='driver-_ID_'>Driver*</label>
                                                        <select id='driver-_ID_' name='_ID_[driver]' class='form-control' required>
                                                            <?php foreach($drivers as $k => $v): ?>
                                                                <option value='<?=$k?>'><?=$v?></option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class='col'>
                                                    <div class='form-group text-right'>
                                                        <button class='btn btn-sm btn-outline-danger remove-database'>Remove</button>
                                                        <div class='form-check mt-2'>
                                                            <input id='passwordless-_ID_' name='_ID_[passwordless]' class='form-check-input' type='checkbox' value='1'>
                                                            <label for='passwordless-_ID_' class='form-check-label'>Passwordless</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>"
                                    >
                                        <?php foreach($servers as $name => $server): ?>
                                            <fieldset class="shadow my-2 p-2">
                                                <div class="row">
                                                    <div class="col">
                                                        <div class="form-group">
                                                            <label for="name-<?=$name?>">Name*</label>
                                                            <input id="name-<?=$name?>" name="<?=$name?>[name]" type="text" class="form-control" value="<?=$name?>" required>
                                                        </div>
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-group">
                                                            <label for="server-<?=$name?>">Server</label>
                                                            <input id="server-<?=$name?>" name="<?=$name?>[server]" type="text" class="form-control" placeholder="127.0.0.1" value="<?=$server['server']?:''?>">
                                                        </div>
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-group">
                                                            <label for="port-<?=$name?>">Port</label>
                                                            <input id="port-<?=$name?>" name="<?=$name?>[port]" type="text" class="form-control" placeholder="3306" value="<?=isset($server['port'])?$server['port']:''?>">
                                                        </div>
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-group">
                                                            <label for="driver-<?=$name?>">Driver*</label>
                                                            <select id="driver-<?=$name?>" name="<?=$name?>[driver]" class="form-control" required>
                                                                <?php foreach($drivers as $k => $v): ?>
                                                                    <option value="<?=$k?>" <?=$server['driver']==$k?'selected':''?>><?=$v?></option>
                                                                <?php endforeach; ?>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-group text-right">
                                                            <button class="btn btn-sm btn-outline-danger remove-database">Remove</button>
                                                            <div class="form-check mt-2">
                                                                <input id="passwordless-<?=$name?>" name="<?=$name?>[passwordless]" class="form-check-input" type="checkbox" value="1" <?=isset($server['passwordless'])&&$server['passwordless']?'checked':''?>>
                                                                <label for="passwordless-<?=$name?>" class="form-check-label">Passwordless</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </fieldset>
                                        <?php endforeach; ?>
                                    </div>
                                    <footer class="card-footer">
                                        <button id="add-database" class="btn btn-outline-secondary">Add database</button>
                                    </footer>
                                </section>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
    </form>
</body>
</html>
